/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pasararchivos;

/**
 *
 * @author Facu
 */
public class PanelProgreso extends javax.swing.JPanel {

    /**
     * Creates new form PanelProgreso
     */
    public PanelProgreso() {
        initComponents();
    }
    
    public void setMaximoBarra(int maximo) {
        barraProgreso.setMaximum(maximo);
    }
    
    public void setValorBarra(int valor) {
        barraProgreso.setValue(valor);
    }
    
    public void setNombreArchivo(String texto) {
        txtNombre.setText(texto);
    }
    
    public void setCantidad(int indice, int total) {
        txtCantidad.setText(indice + "/" + total);
        
        // El texto será visible si se transfiere más de un archivo.
        txtCantidad.setVisible(total > 1);
    }
    
    public void setDatos(String porcentaje, String pasados, String total, String velocidad) {
        txtDatos.setText(porcentaje + " (" + pasados + " / " + total + ") - " + velocidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        txtDatos = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 80));

        txtNombre.setText("Esperando...");

        txtCantidad.setText("0/0");

        txtDatos.setText("0% (0 MB / 0,0 MB) - 0,0 MB/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidad))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDatos)
                        .addGap(0, 230, Short.MAX_VALUE))
                    .addComponent(barraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre)
                    .addComponent(txtCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatos)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
