package pasararchivos;

import com.formdev.flatlaf.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 * @author Facu
 */
public class Panel extends javax.swing.JFrame {

    DefaultListModel<String> modeloArchivos, modeloDispositivos;
    HashMap<String, String> dispositivos;
    
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        
        // Ventana
        setAutoRequestFocus(true);
        setResizable(false);
        setAlwaysOnTop(true);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icono.png"));
        
        labelNoIntenet.setVisible(false);
        
        // Listas
        modeloArchivos = new DefaultListModel<>();
        listaArchivos.setModel(modeloArchivos);
        listaArchivos.setDropMode(DropMode.ON);
        listaArchivos.setTransferHandler(new ListTransferHandler(this));
        
        modeloDispositivos = new DefaultListModel<>();
        listaDispositivos.setModel(modeloDispositivos);
        
        chooser.setMultiSelectionEnabled(true);
        
        dispositivos = new HashMap<>();
    }
    
    public void hayInternet(boolean hay) {
        labelNoIntenet.setVisible(!hay);
    }
    
    public void actualizarLista() {
        HashMap<String, String> nuevo = ClientFinder.getDispositivos();
        
        // Añadir elementos 
        for (String clave: nuevo.keySet()) {
            if (!dispositivos.containsKey(clave)) {
                String nombre = nuevo.get(clave) + " (" + clave + ")";
                modeloDispositivos.addElement(nombre);
            }
        }
        
        // Quitar elementos no existentes
        for (String clave: dispositivos.keySet()) {
            if (!nuevo.containsKey(clave)) {
                String nombre = dispositivos.get(clave) + " (" + clave + ")";
                modeloDispositivos.removeElement(nombre);
            }
        }
        
        dispositivos = nuevo;
    }
    
    public void habilitarBoton() {
        btnTransferir.setEnabled(listaDispositivos.getSelectedIndex() != -1 && !modeloArchivos.isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        texto = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        scrollArchivos = new javax.swing.JScrollPane();
        listaArchivos = new javax.swing.JList<>();
        labelDispositivos = new javax.swing.JLabel();
        scrollDispositivos = new javax.swing.JScrollPane();
        listaDispositivos = new javax.swing.JList<>();
        btnTransferir = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        labelNoIntenet = new javax.swing.JLabel();

        chooser.setDialogTitle("Elegir archivos");
        chooser.setFileFilter(null);

        setTitle("Pasar Archivos 1.2");

        texto.setText("Hola usuario");

        btnSeleccionar.setText("Seleccionar archivos");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        listaArchivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seleccionar archivo" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollArchivos.setViewportView(listaArchivos);

        labelDispositivos.setText("Dispositivos disponibles");

        listaDispositivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDispositivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDispositivosValueChanged(evt);
            }
        });
        scrollDispositivos.setViewportView(listaDispositivos);

        btnTransferir.setText("Transferir");
        btnTransferir.setEnabled(false);
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        labelNoIntenet.setForeground(new java.awt.Color(255, 51, 51));
        labelNoIntenet.setText("No hay conexión de red");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDispositivos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNoIntenet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTransferir)
                                .addGap(8, 8, 8)
                                .addComponent(salir))
                            .addComponent(scrollDispositivos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(scrollArchivos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSeleccionar)
                                    .addComponent(texto))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar)
                .addGap(8, 8, 8)
                .addComponent(scrollArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(labelDispositivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransferir)
                    .addComponent(salir)
                    .addComponent(labelNoIntenet))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int resultado = chooser.showDialog(btnSeleccionar, "Seleccionar");
        
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File[] archivos = chooser.getSelectedFiles();
            
            modeloArchivos.clear();
            
            for (File archivo: archivos) {
                modeloArchivos.addElement(archivo.getAbsolutePath());
            }
            
            habilitarBoton();
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "La transferencia está por iniciar.", "Iniciando transferencia", JOptionPane.OK_CANCEL_OPTION);
        
        // Cancelar la transferencia
        if (res != JOptionPane.OK_OPTION) {
            return;
        }
        
        String[] archivos = new String[modeloArchivos.size()];
        for (int i = 0; i < archivos.length; i++) {
            archivos[i] = (String) modeloArchivos.get(i);
        }
        
        String direccion = "";
        String seleccion = (String) modeloDispositivos.get(listaDispositivos.getSelectedIndex());
        for (String clave: dispositivos.keySet()) {
            String nombre = dispositivos.get(clave) + " (" + clave + ")";
            if (nombre.equals(seleccion)) {
                direccion = clave;
            }
        }
        Transferencia.transferir(archivos, direccion);
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void listaDispositivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDispositivosValueChanged
        habilitarBoton();
    }//GEN-LAST:event_listaDispositivosValueChanged

    public static void initTheme() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        }
        catch (UnsupportedLookAndFeelException e) {
            System.err.println("Error al establecer el tema FlatLaf Light. Intentando cambiar a Nimbus.");
            try {
                for (UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()) {
                    if (info.getName().equals("Nimbus")) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
                System.err.println("No se encontró el tema Nimbus. Usando tema por defecto.");
            }
            catch (ClassNotFoundException | InstantiationException | 
                    IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JLabel labelDispositivos;
    private javax.swing.JLabel labelNoIntenet;
    private javax.swing.JList<String> listaArchivos;
    private javax.swing.JList<String> listaDispositivos;
    private javax.swing.JButton salir;
    private javax.swing.JScrollPane scrollArchivos;
    private javax.swing.JScrollPane scrollDispositivos;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
