/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pasararchivos;

/**
 *
 * @author Facu
 */
public class PanelProgreso extends javax.swing.JPanel {

    /**
     * Creates new form PanelProgreso
     */
    public PanelProgreso() {
        initComponents();
    }
    
    public void setMaximoBarra(int maximo) {
        barraProgreso.setMaximum(maximo);
    }
    
    public void setValorBarra(int valor) {
        barraProgreso.setValue(valor);
    }
    
    public void setNombreArchivo(String texto) {
        txtNombre.setText(texto);
    }
    
    public void setCantidad(int indice, int total) {
        txtCantidad.setText(indice + "/" + total);
        
        // El texto será visible si se transfiere más de un archivo.
        txtCantidad.setVisible(total > 1);
    }
    
    public void setDatos(String porcentaje, String pasados, String total, String velocidad) {
        txtDatos.setText(porcentaje + " (" + pasados + " / " + total + ") - " + velocidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        txtCantidad = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        txtDatos = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 80));

        jPanel1.setMaximumSize(new java.awt.Dimension(16, 16));
        jPanel1.setPreferredSize(new java.awt.Dimension(376, 16));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        txtNombre.setText("Esperando...");
        jPanel1.add(txtNombre);
        jPanel1.add(filler1);

        txtCantidad.setText("0/0");
        jPanel1.add(txtCantidad);

        barraProgreso.setMaximumSize(new java.awt.Dimension(32767, 24));
        barraProgreso.setPreferredSize(new java.awt.Dimension(146, 24));

        txtDatos.setText("0% (0 MB / 0,0 MB) - 0,0 MB/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatos))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatos)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
