package pasararchivos;

/**
 * @author Facu
 */
public class Transfiriendo2 extends javax.swing.JPanel {

    /**
     * Creates new form Transfiriendo
     */
    public Transfiriendo2() {
        initComponents();
        
        System.out.println("Inicializando");
    }
    
    public void setNombre(String archivo) {
        txtNombre.setText("Transfiriendo " + archivo);
    }
    
    public void setDatos(long pasados, long total, float mbs) {
        double progreso = (double) pasados / (double) total;
        
        //txtDatos.setText(Math.floor(progreso * 100) + " (" + (pasados / 1000000) + "MB / " + (total / 1000000) + " MB) - " + mbs + " MB/s");
        txtDatos.setText(pasados + " / " + total + " (" + (progreso * 100) + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        txtDatos = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombre.setText("Transfiriendo Archivo.txt");

        txtDatos.setText("0% (0 MB / 70,8 MB) - 2.3 MB/s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtDatos))
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
